### ISSUE TITLE
[deps] Add openwisp-notifications to requirements

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-monitoring#231]
Since openwisp-notifications has been released, we should add it to the requirements and remove installing `dev` branch from installing in 'install-dev.sh'.

**Comment by nemesisdesign** [comment]
It's being done in https://github.com/openwisp/openwisp-monitoring/pull/228, but we should leave this open and change the goal.
Since we're adding openwisp-notifications to openwisp-controller and openwisp-monitoring depends on openwisp-controller, we can remove the dependency on openwisp-notifications here and leave it only in openwisp-controller.
We can do this once openwisp-controller 0.8 is released.

**Comment by nemesisdesign** [comment]
Closed by #232
