### ISSUE TITLE
[qa] githooks can be used to check commit msg format

### ISSUE THREAD

**Issue by RahulPalve** [openwisp/openwisp-monitoring#289]
Hey, we can use [githooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) to force commit msg format, so that commit is not done until its in correct specification/format.
I want to work on this, can we discuss about this.

githook will look like this in our case:
`.githooks/.commit-msg`
```shell
if [[ $commit_msg =~ ^\[(feature|file|module)\].*#[0-9]+; then
    exit 0
else
    echo "$error_msg"
    exit 1
fi
```
We can do this with all other modules, Please share your thoughts

**Comment by Purhan** [comment]
@RahulPalve We already have this in [openwisp-utils](https://github.com/openwisp/openwisp-utils/blob/master/openwisp-pre-push-hook). Now we only want to add this in the documentation so that everyone starts using it. We already have an issue for it and contributions are welcome for that (https://github.com/openwisp/openwisp2-docs/issues/100).
