### ISSUE TITLE
[bug/change] Decouple status change from alert

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#293]
I describe the problem we have currently with an example.

- we set a tolerance of 5 minutes on the a specific check, say the ping check
- a device is online, then for any reason it's not reachable by the ping check
- the system will wait 5 minutes before sending the alert and changing its status

However, it would be a lot better if we could change the status immediately, but just ensure it does not trigger the alert.

**This is one of those issues which sounds trivial but it's not, so beware.**

**Comment by Purhan** [comment]
Hi @nemesisdesign I was thinking of a possible solution to this problem and I wonder if it is optimal. Please tell me how this sounds:
1. Create a new field for Metric, for example `current_health_status`. This will not be shown to the user but will entirely be in the backend
2. Replace `is_healthy` with this new field so that it behaves like it
3. Update the `is_healthy` field live so that the user can see its status whenever they want, but will only be notified if `current_health_status` changes

This way we can implement this without changing much of the existing code at the cost of a new field in the model. What do you think?
