### ISSUE TITLE
[bug] Traffic total sometimes is very wrong

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#415]
This is happening in the current development version (1.1.0 alpha).

![Screenshot from 2022-07-15 17-05-23](https://user-images.githubusercontent.com/841044/179310866-9af7c09d-8714-4299-947a-3dc4f5ebad34.png)

The total amount in some cases does not match the download + upload exactly, but it should.

**Comment by pandafy** [comment]
I think this is happening because of the approximations. `0.0015`, got rounded off to `0.002`

**Comment by pandafy** [comment]
This issue occurs because we round-off the values of the trace individually using the following method: 

https://github.com/openwisp/openwisp-monitoring/blob/e563520c7765d4e638f8e65b8b8e4095fa2fc4cc/openwisp_monitoring/monitoring/base/models.py#L631-L639

**Note:** The `decimal_places` default to `2`. 

Breaking down the data points from the chart screenshot given in issue description. The `rx_bytes` is `0.0005GB` and the `tx_bytes` is `0.01` GB. Note that these values are obtained after rounding-off the initial values. 

The total bytes that we have in this case is `0.0105GB` which is greater than the control value `0.01`. Hence, the approximation will be done for two decimal places, i.e. `0.01GB`. This results in statcked-bars overshooting the total trace line.


Here's another example: 

![Screenshot from 2022-08-12 15-42-00](https://user-images.githubusercontent.com/32094433/184334083-1542f780-cb54-4058-bde7-eeba90d854df.png)

After rounding off, we have following values in the graph
```
rx_bytes: 20MB
x_bytes: 5.5MB
total_bytes: 30MB
```

We get 30MB here because the approximations are done in GB in the backend. 

```
rx_bytes: 0.02GB
x_bytes: 0.0055GB
total_bytes: 0.030GB
```

Here, the total bytes will be `0.0255GB` which is greater than the control value `0.01`, hence it get rounded off to `0.03` (two decimal places. 

A solution to avoid these problems would be to calculate the `total_bytes` by adding `rx_bytes` and `tx_bytes` after rounding them.

**Comment by nemesisdesign** [comment]
It seems the easiest solution may be to avoid rounding if the chart has the adaptive byte filter configured on it, so we let the JS in the frontend do the rounding.
