### ISSUE TITLE
When using 802.11s there is no channel present and monitoring fails

### ISSUE THREAD

**Issue by mfoxworthy** [openwisp/openwisp-monitoring#520]
When I use an 802.11s configuration and no mesh point is connected, the monitoring agent fails with:

`"Invalid data in \"#/interfaces/4/wireless\", validator says:\n\n'channel' is a required property`

The JSON data being sent also shows no channel"

`{
      "mac": "e8:9f:80:18:7f:bf",
      "type": "wireless",
      "up": true,
      "txqueuelen": 1000,
      "name": "wlan2",
      "wireless": {
        "noise": 0,
        "ssid": "SturdyMesh",
        "country": "US",
        "tx_power": 0,
        "mode": "802.11s"
      },`

This is because there are no attached stations. This is true with auto and explicit channel selection. 

Mike

**Comment by nemesisdesign** [comment]
I am not completely convinced it's because there's no stations connected, but it's something I have encountered when the WiFi interface has problems in working properly. 
This commit here should fixes this corner case with a workaround: https://github.com/openwisp/openwrt-openwisp-monitoring/commit/6709f353f1bd3a99282e9e656e29b5489cd4f1c4, please have a look.
