### ISSUE TITLE
[enhancement] Add support for another timeseries DB

### ISSUE THREAD

**Issue by nepython** [openwisp/openwisp-monitoring#66]
Add support for another timeseries DB, it could be `prometheus`, `opentsdb` or another good option if there's any.
The decision regarding which one to choose must be backed up by convincing research.

Check the discussion [here](https://groups.google.com/forum/#!topic/openwisp/tinsyzJt3BE)

Points to remember:
- we need to implement the current features and make them both work for `Prometheus` and `Influxdb`
- the new timeseries DB that we will support needs to provide an **open source solution for horizontal scaling**, because influxdb does not provide it (has a paid cloud service instead)

**New Findings**:
- There are many timeseries db which are built on top of prometheus and cover up for many essential features missing in prometheus. The best amongst these are [Victoria Metrics](https://github.com/VictoriaMetrics/VictoriaMetrics), [Cortex](https://github.com/cortexproject/cortex) and [Thanos](https://github.com/thanos-io/thanos).
All three projects took off in past 4-5 years, are currently active and open-source (Victoria went open-source [last year](https://blog.usejournal.com/open-sourcing-victoriametrics-f31e34485c2b)).
* Here's a quick comparision between [Cortex and Thanos](https://grafana.com/blog/2019/11/21/promcon-recap-two-households-both-alike-in-dignity-cortex-and-thanos/).
* After going through multiple reviews/ docs/ benchmark comparisions, Victoria Metrics seems impressive. (Check it's [benchmark comparision with influxdb](https://medium.com/@valyala/insert-benchmarks-with-inch-influxdb-vs-victoriametrics-e31a41ae2893))

**NOTE**: This requires #65 to be complete

**Comment by nepython** [comment]
Found this https://github.com/prometheus/influxdb_exporter. It might make things easier. :smile:

**Comment by PabloCastellano** [comment]
We should discuss how to properly setup the metrics exporter, as I have different ideas but I don't know what is the best at the moment.

1. Creating a exporter to be installed in the device is the standard, however due to device limited resources sometimes it might not be the best idea
2. Using something like the pushgateway

There are already exporters for cpu, load, memory, network, etc. They are usually written in Golang, resulting in a quite big executable to put on small devices. So we would have to implement our own ones... in Lua? Doesn't sound very exciting reinventing the wheel in Lua.

By using pushgateway we can reuse the Lua code we have already written.

These are my views, I will try to get some time to think about it so that we can properly discuss it.

**Comment by nemesisdesign** [comment]
Closing, let's continue the discussion in #99.
